server:
  port: 8082
  servlet:
    session:
      timeout: 120m
    encoding:
      charset: UTF-8
      force: true
  tomcat:
    threads:
      min-spare: 30
naver:
  baseUri: https://openapi.naver.com
  uri: /v1/search/blog.json
  clientId: A6Kk8FWlTT51IPPsutdZ
  clientSecret: U6ez5hu5fu